[package]
authors = ["Pollen Robotics <luos@pollen-robotics.com>"]
name = "stm32f0x2"
version = "0.2.0"

[dependencies]
bare-metal = "0.1.1"
cortex-m = "0.4.3"
vcell = "0.1.0"

[dependencies.cortex-m-rt]
optional = true
version = "0.3.12"

[features]
rt = ["cortex-m-rt"]
